export enum SOCKET_EVENTS {
  RUN_CREATED = 'run-created',
  RUN_COMPLETE = 'run-complete',
  MANUAL_RUN_COMPLETE = 'manual-run-complete',
  TIMELINE_UPSERT = 'timeline-upsert',
  BUCKET_UPSERT = 'bucket-upsert',
  UPSERT_NOTIFY_CONFIG = 'upsert-notify-config',
  REMOVE_NOTIFY_CONFIG = 'remove-notify-config',
  PROJECT_UPDATES = 'project-updates',
  PROJECT_PLAN_UPDATES = 'project-plan-updates',
  MEMBERS_UPDATES = 'members-updates',
  INVITES_UPDATES = 'invites-updates',
  TOKENS_UPDATES = 'token-updates',
  ROUTINE_UPDATES = 'routine-updates',
  CURRENT_ROUTINE = 'current-routine',
  DEP_BUILD_START = 'dep-build-start',
  DEP_BUILD_COMPLETE = 'dep-build-complete',
}
